---
- hosts: localhost
  vars_files:
    - local_config.yaml
  tasks:
    - name: HOME synlink
      ansible.builtin.file:
        src: "$PWD/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      loop:
        - .Xresources
        - .Xresources.d

    - name: Create necessary directories
      ansible.builtin.file:
        path: "$HOME/{{ item }}"
        state: directory
      loop:
        - .vim/swap_files
        - .vim/backup_files
        - .vim/undo_files
        - .config/i3
        - .config/dunst
        - .config/polybar

    - name: Generate config file with templates
      template:
        src: templates/{{ item.src }}.j2
        dest: "$HOME/{{ item.dst }}"
      loop:
        - { src: "vim-config", dst: ".vimrc"}
        - { src: "i3-config", dst: ".config/i3/config"}
        - { src: "zsh-config", dst: ".zshrc"}
        - { src: "dunst-config", dst: ".config/dunst/dunstrc"}
        - { src: "polybar-config", dst: ".config/polybar/config.ini"}

    - name: Generate sync executable file
      template:
        src: templates/sync.j2
        dest: "/home/$USER/.local/bin/dotfiles"
        mode: "0755"
