---
- hosts: localhost
  vars_files:
    - local_config.yaml
  tasks:
    - name: .config synlink
      ansible.builtin.file:
        src: "$PWD/.config/{{ item }}"
        dest: "~/.config/{{ item }}"
        state: link
      loop:
        - dunst
        - polybar

    - name: HOME synlink
      ansible.builtin.file:
        src: "$PWD/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      loop:
        - .Xresources
        - .Xresources.d
        - .zshrc

    - name: .vim directories
      ansible.builtin.file:
        path: "~/.vim/{{ item }}"
        state: directory
      loop:
        - swap_files
        - backup_files
        - undo_files
    - name: Generate config file with templates
      template:
        src: templates/{{ item }}.j2
        dest: "$HOME/{{ item }}"
      loop:
        - .vimrc
        - .config/i3/config
    - name: Generate sync executable file
      template:
        src: templates/sync.j2
        dest: "/home/$USER/.local/bin/dotfiles"
        mode: "0755"
